# Generated by Django 5.0 on 2023-12-12 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReachOutMe', '0004_rename_phone_number_contact_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
