# Generated by Django 5.0 on 2023-12-12 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReachOutMe', '0005_alter_contact_email_alter_contact_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
