# Generated by Django 5.0 on 2023-12-12 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ReachOutMe', '0007_rename_created_time_contact_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['name']},
        ),
    ]
